version: 2
# Percy configuration for Tattva Co.
snapshot:
  widths:
    - 375
    - 768
    - 1280
    - 1920
  minHeight: 1024
  percyCSS: ''
discovery:
  allowedHostnames:
    - localhost
    - 127.0.0.1
  disallowedHostnames: []
  networkIdleTimeout: 750
